name: "Add new issues to Ignite GH Project"

on:
  issues:
    types:
      - opened

permissions:
  contents: read
  issues: write
  projects: write

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Add to project
        uses: actions/add-to-project@v0.6.1
        with:
          project-url: ${{ secrets.GH_PROJECT_URL }}
          github-token: ${{ secrets.ADD_TO_PROJECT }}

  label_issues:
    name: Label new issues
    runs-on: ubuntu-latest
    steps:
      - name: Label issue
        run: |
          gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: ${{ secrets.ISSUE_LABEL }}